/**
 * Generates a Dockerfile and fly.toml for a detected app type.
 *
 * Writes both files into `dir` (the extracted user code directory).
 * Any existing Dockerfile is left untouched (kind === "dockerfile").
 */

import fs from "fs/promises";
import path from "path";
import type { AppType } from "./appDetector";

const INTERNAL_PORT = 8080;

// ─── fly.toml v2 ─────────────────────────────────────────────────────────────

function flyToml(appName: string, internalPort: number): string {
  return `# Auto-generated by Small Software Cloud
app = "${appName}"
primary_region = "ord"

[http_service]
  internal_port = ${internalPort}
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
`;
}

// ─── Node.js ──────────────────────────────────────────────────────────────────

function nodeDockerfile(pm: "npm" | "pnpm" | "yarn", startCmd: string): string {
  const installCmd =
    pm === "pnpm"
      ? "RUN npm install -g pnpm && pnpm install --frozen-lockfile"
      : pm === "yarn"
      ? "RUN yarn install --frozen-lockfile"
      // npm ci requires a lockfile; use it when one was committed, otherwise
      // fall back to npm install. The lockfile presence determines pm="npm"
      // detection, so check at build time by testing for package-lock.json.
      : "RUN if [ -f package-lock.json ]; then npm ci --omit=dev; else npm install --omit=dev; fi";

  return `FROM node:20-alpine
WORKDIR /app

COPY package*.json ${pm === "pnpm" ? "pnpm-lock.yaml* " : pm === "yarn" ? "yarn.lock* " : ""}./
${installCmd}

COPY . .

ENV PORT=${INTERNAL_PORT}
ENV NODE_ENV=production
EXPOSE ${INTERNAL_PORT}

CMD ${JSON.stringify(["sh", "-c", startCmd])}
`;
}

// ─── Python ──────────────────────────────────────────────────────────────────

function pythonDockerfile(
  server: "gunicorn" | "uvicorn",
  entrypoint: string
): string {
  const serverPkg = server === "uvicorn" ? "uvicorn[standard]" : "gunicorn";
  const cmd =
    server === "uvicorn"
      ? `uvicorn ${entrypoint} --host 0.0.0.0 --port ${INTERNAL_PORT}`
      : `gunicorn ${entrypoint} --bind 0.0.0.0:${INTERNAL_PORT} --workers 2`;

  return `FROM python:3.11-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt ${serverPkg}

COPY . .

ENV PORT=${INTERNAL_PORT}
EXPOSE ${INTERNAL_PORT}

CMD ["sh", "-c", "${cmd}"]
`;
}

// ─── Static (nginx) ───────────────────────────────────────────────────────────

function staticDockerfile(): string {
  return `FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80
`;
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function generateDeployFiles(
  dir: string,
  appName: string,
  appType: AppType
): Promise<{ internalPort: number }> {
  let dockerfile: string;
  let internalPort = INTERNAL_PORT;

  switch (appType.kind) {
    case "dockerfile":
      // User-supplied Dockerfile: don't overwrite it, just write fly.toml
      // Try to sniff the EXPOSE port; fall back to 8080
      try {
        const raw = await fs.readFile(path.join(dir, "Dockerfile"), "utf8");
        const exposeMatch = raw.match(/^EXPOSE\s+(\d+)/im);
        if (exposeMatch) internalPort = parseInt(exposeMatch[1]);
      } catch {
        // ignore
      }
      await fs.writeFile(path.join(dir, "fly.toml"), flyToml(appName, internalPort));
      return { internalPort };

    case "node":
      dockerfile = nodeDockerfile(appType.packageManager, appType.startCommand);
      break;

    case "python":
      dockerfile = pythonDockerfile(appType.server, appType.entrypoint);
      break;

    case "static":
      dockerfile = staticDockerfile();
      internalPort = 80;
      break;
  }

  await fs.writeFile(path.join(dir, "Dockerfile"), dockerfile);
  await fs.writeFile(path.join(dir, "fly.toml"), flyToml(appName, internalPort));

  return { internalPort };
}
